version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8000:4242"
    env_file:
      - .env  # Loads environment variables from .env file
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/full_dump.sql:/docker-entrypoint-initdb.d/full_dump.sql  # ✅ ADD THIS LINE
  appointment_service:
    build:
      context: ./appointment_service
    container_name: appointment_service
    ports:
      - "8001:4201"
    env_file:
      - ./appointment_service/.env
    depends_on:
      - appointment_db

  appointment_db:
    image: postgres:latest
    container_name: postgres_appointment_db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ./appointment_service/.env
    ports:
      - "5434:5432"
    volumes:
      - appointment_db_data:/var/lib/postgresql/data
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8002:4202"
    env_file:
      - ./user_service/.env
    depends_on:
      - user_db

  user_db:
    image: postgres:latest
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ./user_service/.env
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  kafka:  
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=OF888ljeSx2KZmND0yvrpA
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  postgres_data:
  appointment_db_data:
  kafka_data:
  user_db_data:
